[package]
name = "mc-nano"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
anyhow = "1.0.86"
async-std = "1.12.0"
async-trait = "0.1.80"
protocol_derive = { path = "protocol_derive" }
