[package]
name = "crafti_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-std = "1.12.0"
async-trait = "0.1.80"
thiserror = "1.0.61"
crafti_protocol_derive = { path = "crafti_protocol_derive" }
